### ISSUE TITLE
Can not run demo

### ISSUE THREAD

**Issue by wclr** [canjs/worker-render#10]
Installed (npm install) and tried to run demo:

```
error ReferenceError: Error loading "demo/circles" at http://localhost:63342/.../worker-render/demo/circles.js(…) ReferenceError: Error loading "demo/circles" at http://localhost:63342/../worker-render/demo/circles.js
global is not defined
```

**Comment by justinbmeyer** [comment]
Do you need a dev install for this to work?

**Comment by wclr** [comment]
> Do you need a dev install for this to work?

What do you mean? dev deps were installed.

**Comment by justinbmeyer** [comment]
I wasn't sure if you were installing this into another project as a dependency.  If you did that, dev deps are not installed.

**Comment by wclr** [comment]
@matthewp 
Some demos still fail to load for me. For example todomvc app can not load stache.

**Comment by matthewp** [comment]
Can you post the error you get? No problems here.
